In [1]:
import torch

In [2]:
one_d_tensor = torch.LongTensor([0])

one_d_tensor.shape, one_d_tensor.dim(), one_d_tensor

(torch.Size([1]), 1, tensor([0]))

In [3]:
one_d_tensor = torch.LongTensor([0, 1, 2])

one_d_tensor.shape, one_d_tensor.dim(), one_d_tensor

(torch.Size([3]), 1, tensor([0, 1, 2]))

In [5]:
two_d_tensor = torch.LongTensor([[0, 1, 2], [3, 4, 5]])

two_d_tensor.shape, two_d_tensor.dim(), two_d_tensor

(torch.Size([2, 3]),
 2,
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [6]:
one_d_tensor = torch.LongTensor([0, 1, 2])

one_d_tensor.shape, one_d_tensor.dim(), one_d_tensor

(torch.Size([3]), 1, tensor([0, 1, 2]))

In [8]:
two_d_tensor = one_d_tensor.unsqueeze(0)

two_d_tensor.shape, two_d_tensor.dim(), two_d_tensor

(torch.Size([1, 3]), 2, tensor([[0, 1, 2]]))

In [9]:
two_d_tensor.numpy()

array([[0, 1, 2]])

In [11]:
# detach removes a tensor from a computational graph
two_d_tensor.detach().numpy()

array([[0, 1, 2]])